schema_version = "1.0.0"

id = "barrel_pcg_demo"
version = "1.0.0"
name = "Barrel PCG Demo"
tagline = "Ch9 of Blender Scripting with Python by Isabel Lupiani"
maintainer = "Isabel Lupiani <a@b.com>"
type = "add-on"

website = "https://github.com/iklupiani/test_add_on_remote"

tags = ["Modeling", "Mesh"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]

copyright = [
  "2018-2024 Isabel Lupiani",
  "2024 Apress",
]
