schema_version = "1.0.0"

id = "projection_painting_helper"
version = "2.0.0"
name = "Projection Painting Helper"
tagline = "Ch8 Examples of Blender Scripting with Python by Isabel Lupiani"
maintainer = "Isabel Lupiani <a@b.com>"
type = "add-on"

tags = ["Paint", "UV"]

blender_version_min = "4.3.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-2.0-or-later",
]

copyright = [
  "2018-2024 Isabel Lupiani",
  "2024 Apress",
]
